-- CREATE TABLE employees2 FOR IMPORT CSV FILE INTO THIS TABLE
CREATE TABLE employees2(
	employee_id INT PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	department VARCHAR(50),
	salary NUMERIC(10,2),
	joining_date DATE,
	age INT
);


-- IMPORT CSV FILE QUERY
COPY EMPLOYEES2(EMPLOYEE_ID,FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, SALARY, JOINING_DATE,	AGE)
FROM 'D:\Satish Dhawale Pg admin\employee_data.csv' --THIS IS PATH OF CSV FILE.....IF HAVE YOU ERROR THEN YOU CHANGE YOUR BACK SLASH LIKE '/', '\'
DELIMITER',' CSV HEADER;

--FETCH DATA OF employees2 TABLE
SELECT * FROM employees2;


